### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by RaviKumarSingh-Mckinsey** [techwithtim/AI-Web-Scraper#12]
@techwithtim techwithtim , Like others , Iam also facing same issue , Can you please check it out and suggest next step. 

```
Ravi_Kumar_Singh@M-D7TVQ07C1W AI-Web-Scraper % streamlit run main.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8502
  Network URL: http://10.18.4.78:8502

Connecting to Scraping Browser...
2024-12-07 12:45:33.355 Uncaught app exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/Ravi_Kumar_Singh/Downloads/AI-Web-Scraper/main.py", line 20, in <module>
    dom_content = scrape_website(url)
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/Ravi_Kumar_Singh/Downloads/AI-Web-Scraper/scrape.py", line 14, in scrape_website
    sbr_connection = ChromiumRemoteConnection(SBR_WEBDRIVER, "goog", "chrome")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/chromium/remote_connection.py", line 36, in __init__
    super().__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py", line 365, in __init__
    self._proxy_url = self._client_config.get_proxy_url()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/client_config.py", line 274, in get_proxy_url
    "https_proxy" if self.remote_server_addr.startswith("https://") else "http_proxy",
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by LightsGuardian117** [comment]
Had the same problem. Replace your scrape.py code with the following (and remember to change your Llama version to the one you're using): 

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from bs4 import BeautifulSoup
from dotenv import load_dotenv
import os

load_dotenv()

# Path to chromedriver.exe
CHROMEDRIVER_PATH = os.getenv("CHROMEDRIVER_PATH")  # Ensure this is set in your .env file


def scrape_website(website):
    print("Connecting to ChromeDriver...")

    # Set up Chrome options
    chrome_options = Options()
    chrome_options.add_argument("--headless")  # Run in headless mode (optional)
    chrome_options.add_argument("--disable-gpu")  # Disable GPU (optional for headless)

    # Set up ChromeDriver service
    service = Service(CHROMEDRIVER_PATH)

    # Initialize the WebDriver
    with webdriver.Chrome(service=service, options=chrome_options) as driver:
        driver.get(website)
        print("Waiting captcha to solve...")
        solve_res = driver.execute_script(
            "return {status: 'solved'};"  # Replace with actual captcha-solving logic
        )
        print("Captcha solve status:", solve_res["status"])
        print("Navigated! Scraping page content...")
        html = driver.page_source
        return html


def extract_body_content(html_content):
    soup = BeautifulSoup(html_content, "html.parser")
    body_content = soup.body
    if body_content:
        return str(body_content)
    return ""


def clean_body_content(body_content):
    soup = BeautifulSoup(body_content, "html.parser")

    for script_or_style in soup(["script", "style"]):
        script_or_style.extract()

    # Get text or further process the content
    cleaned_content = soup.get_text(separator="\n")
    cleaned_content = "\n".join(
        line.strip() for line in cleaned_content.splitlines() if line.strip()
    )

    return cleaned_content


def split_dom_content(dom_content, max_length=6000):
    return [
        dom_content[i : i + max_length] for i in range(0, len(dom_content), max_length)
    ]

**Comment by LightsGuardian117** [comment]
I'm guessing you might be using windows? If so the error might be due to the cromedriver file not being cromedriver.exe in the code. I tried the following code, and it worked for me (hope this works, and please remember to select the correct Llama version in the code) : 

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from bs4 import BeautifulSoup
from dotenv import load_dotenv
import os

load_dotenv()

# Path to chromedriver.exe
CHROMEDRIVER_PATH = os.getenv("CHROMEDRIVER_PATH")  # Ensure this is set in your .env file


def scrape_website(website):
    print("Connecting to ChromeDriver...")

    # Set up Chrome options
    chrome_options = Options()
    chrome_options.add_argument("--headless")  # Run in headless mode (optional)
    chrome_options.add_argument("--disable-gpu")  # Disable GPU (optional for headless)

    # Set up ChromeDriver service
    service = Service(CHROMEDRIVER_PATH)

    # Initialize the WebDriver
    with webdriver.Chrome(service=service, options=chrome_options) as driver:
        driver.get(website)
        print("Waiting captcha to solve...")
        solve_res = driver.execute_script(
            "return {status: 'solved'};"  # Replace with actual captcha-solving logic
        )
        print("Captcha solve status:", solve_res["status"])
        print("Navigated! Scraping page content...")
        html = driver.page_source
        return html


def extract_body_content(html_content):
    soup = BeautifulSoup(html_content, "html.parser")
    body_content = soup.body
    if body_content:
        return str(body_content)
    return ""


def clean_body_content(body_content):
    soup = BeautifulSoup(body_content, "html.parser")

    for script_or_style in soup(["script", "style"]):
        script_or_style.extract()

    # Get text or further process the content
    cleaned_content = soup.get_text(separator="\n")
    cleaned_content = "\n".join(
        line.strip() for line in cleaned_content.splitlines() if line.strip()
    )

    return cleaned_content


def split_dom_content(dom_content, max_length=6000):
    return [
        dom_content[i : i + max_length] for i in range(0, len(dom_content), max_length)
    ]

**Comment by LightsGuardian117** [comment]
If you are using windows the error might be due to the chromedriver file being referred to as just chromedriver and not chromedriver.exe in the code. the following code fixed it for me. (please remember to account for the correct Llama version in your code): 

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from bs4 import BeautifulSoup
from dotenv import load_dotenv
import os

load_dotenv()

# Path to chromedriver.exe
CHROMEDRIVER_PATH = os.getenv("CHROMEDRIVER_PATH")  # Ensure this is set in your .env file


def scrape_website(website):
    print("Connecting to ChromeDriver...")

    # Set up Chrome options
    chrome_options = Options()
    chrome_options.add_argument("--headless")  # Run in headless mode (optional)
    chrome_options.add_argument("--disable-gpu")  # Disable GPU (optional for headless)

    # Set up ChromeDriver service
    service = Service(CHROMEDRIVER_PATH)

    # Initialize the WebDriver
    with webdriver.Chrome(service=service, options=chrome_options) as driver:
        driver.get(website)
        print("Waiting captcha to solve...")
        solve_res = driver.execute_script(
            "return {status: 'solved'};"  # Replace with actual captcha-solving logic
        )
        print("Captcha solve status:", solve_res["status"])
        print("Navigated! Scraping page content...")
        html = driver.page_source
        return html


def extract_body_content(html_content):
    soup = BeautifulSoup(html_content, "html.parser")
    body_content = soup.body
    if body_content:
        return str(body_content)
    return ""


def clean_body_content(body_content):
    soup = BeautifulSoup(body_content, "html.parser")

    for script_or_style in soup(["script", "style"]):
        script_or_style.extract()

    # Get text or further process the content
    cleaned_content = soup.get_text(separator="\n")
    cleaned_content = "\n".join(
        line.strip() for line in cleaned_content.splitlines() if line.strip()
    )

    return cleaned_content


def split_dom_content(dom_content, max_length=6000):
    return [
        dom_content[i : i + max_length] for i in range(0, len(dom_content), max_length)
    ]

**Comment by LightsGuardian117** [comment]
If you are using windows the error might be due to the chromedriver file being referred to as just chromedriver and not chromedriver.exe in the code. the following code fixed it for me: (please remember to account for the correct Llama version in your code)
```
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from bs4 import BeautifulSoup
from dotenv import load_dotenv
import os

load_dotenv()

# Path to chromedriver.exe
CHROMEDRIVER_PATH = os.getenv("CHROMEDRIVER_PATH")  # Ensure this is set in your .env file


def scrape_website(website):
    print("Connecting to ChromeDriver...")

    # Set up Chrome options
    chrome_options = Options()
    chrome_options.add_argument("--headless")  # Run in headless mode (optional)
    chrome_options.add_argument("--disable-gpu")  # Disable GPU (optional for headless)

    # Set up ChromeDriver service
    service = Service(CHROMEDRIVER_PATH)

    # Initialize the WebDriver
    with webdriver.Chrome(service=service, options=chrome_options) as driver:
        driver.get(website)
        print("Waiting captcha to solve...")
        solve_res = driver.execute_script(
            "return {status: 'solved'};"  # Replace with actual captcha-solving logic
        )
        print("Captcha solve status:", solve_res["status"])
        print("Navigated! Scraping page content...")
        html = driver.page_source
        return html


def extract_body_content(html_content):
    soup = BeautifulSoup(html_content, "html.parser")
    body_content = soup.body
    if body_content:
        return str(body_content)
    return ""


def clean_body_content(body_content):
    soup = BeautifulSoup(body_content, "html.parser")

    for script_or_style in soup(["script", "style"]):
        script_or_style.extract()

    # Get text or further process the content
    cleaned_content = soup.get_text(separator="\n")
    cleaned_content = "\n".join(
        line.strip() for line in cleaned_content.splitlines() if line.strip()
    )

    return cleaned_content


def split_dom_content(dom_content, max_length=6000):
    return [
        dom_content[i : i + max_length] for i in range(0, len(dom_content), max_length)
    ]
```

**Comment by LightsGuardian117** [comment]
use that code in your scrape.py folder

**Comment by LightsGuardian117** [comment]
If you are using windows the error might be due to the chromedriver file being referred to as just chromedriver and not chromedriver.exe in the code.

**Comment by RaviKumarSingh-Mckinsey** [comment]
No , using MAC book
